[program:chrome_do_action_server]
command=node dist/server.js --port 12345 --log-dir /tmp/chrome/
environment=NODE_ENV=production
directory=/var/www/chrome_do_action/server
stopwaitsecs=5
restart=always
stderr_logfile=/tmp/chrome/supervisor-err.log
stdout_logfile=/tmp/chrome/supervisor-out.log
user=root
